spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_DEV_USER}
    password: ${DB_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: ${REDIS_PORT}
      host: localhost
      database: ${REDIS_DATABASE}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis
    redis:
      time-to-live: 3600  # 캐시 항목의 TTL(Time To Live)을 1시간으로 설정

jwt:
  secret:
    key: ${JWT_KEY}

  token:
    prefix: ${JWT_PREFIX}
    refreshPrefix: ${REFRESH_PREFIX}
    blackListPrefix: ${BLACK_PREFIX}
    expiration: ${JWT_EXPIRATION}
    refreshExpiration: ${REFRESH_EXPIRATION}
    blackListExpiration: ${BLACK_EXPIRATION}
security:
  bcrypt:
    cost: ${SECURITY_COST}
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace