spring:
  datasource:
    url: jdbc:mysql://${db.url}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  config:
    import: myinfo.yml

  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
      database: ${redis.database}

# jwt token secret keys
jwt:
  secret:
    key: ${jwt.key}
  token:
    prefix: ${jwt.prefix}
    expiration: ${jwt.expiration}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

security:
  bcrypt:
    cost: ${security.cost}

