name: CI/CD for Cheer-Ha

on:
  push:
    branches: [release/1.0.1]
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Remove Existing .env File
        run: rm -f .env

      - name: Create .env file
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Debug ENV_FILE
        run: cat .env

      - name: Chmod gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --parallel --daemon --max-workers=2 -x test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Delete Old Docker Image
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d \
          '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' \
          https://hub.docker.com/v2/users/login/ | jq -r .token)
        
          curl -X DELETE \
          -H "Authorization: Bearer $TOKEN" \
          "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/cheer-ha/tags/latest/"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cheer-ha:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cheer-ha:latest

  deploy:
    name: Deploy to AWS Auto Scaling Group
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Trigger ASG Rolling Update
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name cheerha-auto
